version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "vitest"
          - "@vitest/*"
          - "typescript*"
          - "esbuild"
          - "knip"
          - "npm-run-all"
          - "@vscode/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      runtime-dependencies:
        patterns:
          - "ts-pattern"
        update-types:
          - "major"
          - "minor"
          - "patch"
